# Generated by Django 4.2.2 on 2023-06-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='matricula',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
    ]
